# Generated by Django 4.0.2 on 2022-02-22 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PracticeApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='practice',
            name='salary',
            field=models.IntegerField(null=True),
        ),
    ]
