# Generated by Django 4.0.2 on 2022-02-22 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PracticeApp', '0002_practice_salary'),
    ]

    operations = [
        migrations.DeleteModel(
            name='practice',
        ),
    ]
