# Generated by Django 4.0.2 on 2022-02-23 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PracticeApp', '0005_department_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='department_code',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
