# Generated by Django 4.0.2 on 2022-02-23 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PracticeApp', '0007_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='students',
        ),
        migrations.DeleteModel(
            name='Testing',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
