# Generated by Django 4.0.4 on 2022-06-03 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapplication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefferelForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='applicantsinfo',
            name='interest',
            field=models.CharField(default=None, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='applicantsinfo',
            name='cv',
            field=models.FileField(default=None, max_length=250, upload_to='cv/'),
        ),
    ]
