# Generated by Django 4.0.4 on 2022-06-03 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapplication', '0002_refferelform_applicantsinfo_interest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantsinfo',
            name='cv',
            field=models.FileField(default=None, max_length=250, upload_to='media/cv'),
        ),
    ]
