# Generated by Django 4.0.2 on 2022-02-27 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=40)),
                ('Phone', models.CharField(max_length=20)),
                ('Address', models.CharField(max_length=100)),
                ('class_name', models.IntegerField()),
                ('result', models.FloatField()),
            ],
        ),
    ]
