# Generated by Django 4.0.2 on 2022-02-27 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0002_alter_studentdetails_result'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentdetails',
            old_name='Address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='studentdetails',
            old_name='Phone',
            new_name='phone',
        ),
    ]
