# Generated by Django 4.0.2 on 2022-02-14 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_alter_album_num_stars_alter_musician_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='num_stars',
            field=models.IntegerField(choices=[(1, 'Worstttt'), (2, 'Bad'), (3, 'Not Bad'), (4, 'Good'), (5, 'Excellent!')]),
        ),
    ]
