# Generated by Django 4.0.4 on 2022-06-06 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('job_title', models.CharField(max_length=20)),
                ('applicants_cv', models.FileField(upload_to='applicants_cv')),
            ],
        ),
    ]
