# Generated by Django 4.0.4 on 2022-06-06 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='applicants_cv',
            field=models.FileField(upload_to='media/applicants_cv'),
        ),
    ]
