# Generated by Django 4.0.4 on 2022-06-06 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_candidate_applicants_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='applicants_cv',
            field=models.FileField(upload_to='applicants_cv'),
        ),
    ]
